apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: caddy
  name: caddy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: caddy
  strategy: {}
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - image: caddy:2.6
        name: caddy
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsGroup: 3000
          capabilities:
            drop:
             - all
            add:
             - NET_RAW
             - CHOWN
             - KILL
             - SETGID
             - SETUID
            #  - NET_ADMIN
            #  - SYS_ADMIN
            #  - SYS_TIME
            #  - SYS_RESOURCE
            #  - MAC_OVERRIDE
            #  - SETFCAP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
