apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: caddy
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: caddy
    spec:
      containers:
      - image: caddy:2.6
        name: caddy
        resources: {}
status: {}
