name: Policy Check
on: 
#   push:
#     branches:
#     - main
#     - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '**.yaml'

jobs:
  polaris-scan-actions:
    runs-on: ubuntu-22.04
    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Setup Polaris
      uses: fairwindsops/polaris/.github/actions/setup-polaris@master
      with:
        version: 5.0.0

    - name: Print version
      run: polaris version

    - name: Policy check
      run: polaris audit --audit-path . --format=pretty --only-show-failed-tests true --set-exit-code-below-score 99
# --color=false
