name: Policy Check
on: 
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '**.yaml'

jobs:
 kubescore-scan:
    runs-on: ubuntu-22.04
    container: ralphotowo/kube-score
    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Static check
      run: kube-score score  --kubernetes-version v1.22 --output-format ci **/*.yaml
